/* Eduneeds shared, frontend-only notification manager. */
(function (window) {
    'use strict';
    var LIMIT = 100, PREFIX = 'eduneeds_notifications_', initialized = false;
    function user() {
        if (window.EduneedsAuth && window.EduneedsAuth.getCurrentUser) return window.EduneedsAuth.getCurrentUser();
        try { var saved = JSON.parse(sessionStorage.getItem('eduneeds_current_user') || 'null'); return saved && saved.id ? saved : null; } catch (e) { return null; }
    }
    function key() { var current = user(); return current ? PREFIX + current.id : ''; }
    function read() { var storageKey = key(); if (!storageKey) return []; try { var data = JSON.parse(localStorage.getItem(storageKey) || '[]'); return Array.isArray(data) ? data : []; } catch (e) { return []; } }
    function write(items) { var storageKey = key(); if (!storageKey) return false; try { localStorage.setItem(storageKey, JSON.stringify(items.slice(0, LIMIT))); return true; } catch (e) { return false; } }
    function icon(type) { return { wallet_funding: 'account_balance_wallet', purchase: 'shopping_cart', insufficient_balance: 'error', account: 'person' }[type] || 'notifications'; }
    function relativeTime(date) { var diff = Math.max(0, Date.now() - new Date(date).getTime()), minutes = Math.floor(diff / 60000); if (minutes < 1) return 'Just now'; if (minutes < 60) return minutes + ' min ago'; var hours = Math.floor(minutes / 60); if (hours < 24) return hours + ' hr ago'; var days = Math.floor(hours / 24); return days === 1 ? 'Yesterday' : new Date(date).toLocaleDateString(); }
    function add(details) { var current = user(); if (!current || !details || !details.title) return null; var item = { id: 'NTF-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 7), type: details.type || 'general', title: String(details.title), message: String(details.message || ''), amount: Number(details.amount) || 0, read: false, createdAt: new Date().toISOString(), userId: current.id }; var items = read(); items.unshift(item); write(items); refresh(); return item; }
    function markAsRead(id) { var items = read(), changed = false; items.forEach(function (item) { if (item.id === id && !item.read) { item.read = true; changed = true; } }); if (changed) { write(items); refresh(); } }
    function markAllAsRead() { var items = read(), changed = false; items.forEach(function (item) { if (!item.read) { item.read = true; changed = true; } }); if (changed) { write(items); refresh(); } }
    function unreadCount() { return read().filter(function (item) { return !item.read; }).length; }
    function styles() { if (document.getElementById('notification-styles')) return; var style = document.createElement('style'); style.id = 'notification-styles'; style.textContent = '.notification-host{position:relative}.notification-badge{position:absolute;top:-5px;right:-6px;min-width:17px;height:17px;padding:0 4px;border-radius:99px;background:#dc2626;color:#fff;font:700 10px/17px Inter,Arial,sans-serif;text-align:center}.notification-badge[hidden]{display:none}.notification-panel{position:absolute;top:calc(100% + 10px);right:0;z-index:1500;width:min(380px,calc(100vw - 24px));max-height:min(520px,70vh);overflow:auto;background:var(--card-bg,#fff);color:var(--text-color,#111827);border:1px solid var(--border-color,#e5e7eb);border-radius:12px;box-shadow:0 16px 36px rgba(0,0,0,.18)}.notification-panel[hidden]{display:none}.notification-head{display:flex;align-items:center;justify-content:space-between;padding:14px 16px;border-bottom:1px solid var(--border-color,#e5e7eb)}.notification-head strong{font-family:Manrope,Arial,sans-serif}.notification-action{border:0;background:transparent;color:#0040a1;font:600 12px Inter,Arial,sans-serif;cursor:pointer;padding:4px}.notification-item{display:flex;gap:10px;padding:13px 16px;border-bottom:1px solid var(--border-color,#e5e7eb);cursor:pointer}.notification-item:hover{background:rgba(0,64,161,.06)}.notification-item.unread{background:rgba(0,64,161,.08)}.notification-item-icon{color:#0040a1;font-size:21px}.notification-item.error .notification-item-icon{color:#dc2626}.notification-copy{min-width:0;flex:1}.notification-title{display:block;font-size:14px;font-weight:600}.notification-message,.notification-time{display:block;margin-top:3px;font-size:12px;color:#6b7280;line-height:1.4}.notification-empty{text-align:center;padding:32px 18px;color:#6b7280;font-size:14px}.notification-empty .material-symbols-outlined{display:block;font-size:28px;margin-bottom:8px;color:#0040a1}.notification-footer{padding:11px 16px;font-size:12px;color:#6b7280;text-align:center}body.dark-mode .notification-panel{background:#141e2f;color:#e8edf5;border-color:#1e2a3d}body.dark-mode .notification-head,body.dark-mode .notification-item{border-color:#1e2a3d}body.dark-mode .notification-message,body.dark-mode .notification-time,body.dark-mode .notification-empty,body.dark-mode .notification-footer{color:#9aabc0}@media(max-width:575px){.notification-panel{position:fixed;top:64px;right:12px;width:calc(100vw - 24px);max-height:calc(100vh - 82px)}}'; document.head.appendChild(style); }
    function makePanel(host, button) { var panel = document.createElement('section'); panel.className = 'notification-panel'; panel.hidden = true; panel.setAttribute('role', 'region'); panel.setAttribute('aria-label', 'Notifications'); host.appendChild(panel); function close() { panel.hidden = true; button.setAttribute('aria-expanded', 'false'); } function render() { var items = read(); panel.replaceChildren(); var header = document.createElement('div'); header.className = 'notification-head'; var heading = document.createElement('strong'); heading.textContent = 'Notifications'; header.appendChild(heading); if (items.some(function (item) { return !item.read; })) { var allRead = document.createElement('button'); allRead.className = 'notification-action'; allRead.type = 'button'; allRead.textContent = 'Mark all as read'; allRead.addEventListener('click', markAllAsRead); header.appendChild(allRead); } panel.appendChild(header); if (!items.length) { var empty = document.createElement('div'); empty.className = 'notification-empty'; var emptyIcon = document.createElement('span'); emptyIcon.className = 'material-symbols-outlined'; emptyIcon.textContent = 'notifications_none'; var text = document.createElement('div'); text.textContent = "No notifications yet. You'll see wallet activity and purchases here."; empty.append(emptyIcon, text); panel.appendChild(empty); } else items.forEach(function (item) { var row = document.createElement('div'); row.className = 'notification-item ' + (item.read ? '' : 'unread ') + (item.type === 'insufficient_balance' ? 'error' : ''); row.tabIndex = 0; var itemIcon = document.createElement('span'); itemIcon.className = 'notification-item-icon material-symbols-outlined'; itemIcon.textContent = icon(item.type); var copy = document.createElement('div'); copy.className = 'notification-copy'; var title = document.createElement('span'); title.className = 'notification-title'; title.textContent = item.title; var message = document.createElement('span'); message.className = 'notification-message'; message.textContent = item.message; var time = document.createElement('span'); time.className = 'notification-time'; time.textContent = relativeTime(item.createdAt); copy.append(title, message, time); row.append(itemIcon, copy); row.addEventListener('click', function () { markAsRead(item.id); }); row.addEventListener('keydown', function (event) { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); markAsRead(item.id); } }); panel.appendChild(row); }); var footer = document.createElement('div'); footer.className = 'notification-footer'; footer.textContent = 'Recent notifications'; panel.appendChild(footer); }
        button.addEventListener('click', function () { var open = panel.hidden; document.querySelectorAll('.notification-panel').forEach(function (other) { other.hidden = true; }); if (open) { render(); panel.hidden = false; button.setAttribute('aria-expanded', 'true'); } else close(); }); document.addEventListener('click', function (event) { if (!host.contains(event.target)) close(); }); document.addEventListener('keydown', function (event) { if (event.key === 'Escape') close(); }); host._notificationRender = render;
    }
    function init() { if (!document.querySelector('.notification-host')) styles(); document.querySelectorAll('.icon-btn[aria-label="Notifications"]').forEach(function (button) { if (button.dataset.notificationsReady) return; button.dataset.notificationsReady = 'true'; var host = document.createElement('div'); host.className = 'notification-host'; button.parentNode.insertBefore(host, button); host.appendChild(button); button.setAttribute('aria-haspopup', 'true'); button.setAttribute('aria-expanded', 'false'); var badge = button.querySelector('.notification-dot') || document.createElement('span'); badge.className = 'notification-badge'; if (!badge.parentNode) button.appendChild(badge); makePanel(host, button); }); refresh(); initialized = true; }
    function refresh() { var count = unreadCount(); document.querySelectorAll('.notification-host').forEach(function (host) { var badge = host.querySelector('.notification-badge'); if (badge) { badge.hidden = count === 0; badge.textContent = count > 99 ? '99+' : String(count); } if (host._notificationRender) host._notificationRender(); }); }
    window.addEventListener('storage', function (event) { if (event.key && event.key.indexOf(PREFIX) === 0) refresh(); });
    window.EduneedsNotifications = { add: add, getAll: read, getUnread: function () { return read().filter(function (item) { return !item.read; }); }, markAsRead: markAsRead, markAllAsRead: markAllAsRead, clearAll: function () { if (window.confirm('Clear all notifications?')) { write([]); refresh(); } }, refresh: refresh, render: refresh };
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init); else init(); document.addEventListener('componentsLoaded', init);
}(window));
